[project]
name = "fizz"
version = "0.1.0"
description = "A clean and easy-to-use CLI timer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["pytest>=8.4.1"]
